# fly.toml app configuration file generated for proid on 2025-07-16T01:21:17+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'proid'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
